stages:
  data_correction:
    cmd: python src/classifier/pipeline/stage_data_correction.py
    params:
    - data_correction.name
  data_transformation:
    cmd: python src/classifier/pipeline/stage_03_data_transformation.py
    outs:
    - artifacts/data_transformation_dt3_batch_50000
    params:
    - data_transformation.number
  model_evaluation:
    cmd: python src/classifier/pipeline/stage_05_model_evaluation.py
    deps:
    - artifacts/test_data_correction
    params:
    - model_evaluation
  model_trainer:
    cmd: python src/classifier/pipeline/stage_04_model_training.py
    deps:
    - artifacts/data_transformation_dt3_batch_50000
    params:
    - model_trainer.model_name
  test_data_correction:
    cmd: python src/classifier/pipeline/stage_test_data_correction.py
    outs:
    - artifacts/test_data_correction
